
version: '3'

services:
  PostgreSQL:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    ports: 
      - "5432:5432"
    env_file:
      - docker.env


  pgadmin:
    # links:
    # - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    # volumes:
    # - /data/pgadmin:/root/.pgadmin
    env_file:
    - docker.env


      #
      #back:
      #    depends_on:
      #      - PostgreSQL
      #    image: back
    # environment:
    #   REACT_APP_42_API_CLIENT: 42_API_CLIENT
    #   REACT_APP_42_API_SECRET: 42_API_SECRET
      #    container_name: back
      #    restart: always
      #    init: true
      #
      #
      #front :
      #    depends_on:
      #      - back
      #    build: ./srcs/front
      #    image: front
      #    container_name: front
      #    restart: always
      #    ports:
      #      - 4000:4000
      #


